"""phone codes and password change time

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 13:59:18.718956

"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_codes_phone'), ['phone'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')

    with op.batch_alter_table('phone_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_codes_phone'))
        batch_op.drop_index(batch_op.f('ix_phone_codes_created_at'))

    op.drop_table('phone_codes')
    # ### end Alembic commands ###
