"""order city

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 14:56:15.072878

"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_city'), ['city'], unique=False)

    # ### end Alembic commands ###

    # Data: masters typed their city as free text before; map it to the canonical list
    # ("бишкек " -> "Бишкек") so city matching works, and take old orders' city from their address.
    from app.cities import normalize_city

    bind = op.get_bind()
    masters = sa.table("masters", sa.column("id", sa.Integer), sa.column("city", sa.String))
    for master_id, city in bind.execute(sa.select(masters.c.id, masters.c.city)).all():
        canonical = normalize_city(city)
        if city and canonical and canonical != city:
            bind.execute(masters.update().where(masters.c.id == master_id).values(city=canonical))

    orders = sa.table("orders", sa.column("id", sa.Integer), sa.column("address", sa.String),
                      sa.column("city", sa.String))
    for order_id, address in bind.execute(sa.select(orders.c.id, orders.c.address)).all():
        first_part = (address or "").split(",")[0]
        canonical = normalize_city(first_part)
        if canonical:
            bind.execute(orders.update().where(orders.c.id == order_id).values(city=canonical))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_city'))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
