"""email verification codes, unique email

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 10:41:13.173256

"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_target'), ['target'], unique=False)

    with op.batch_alter_table('phone_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_phone_codes_created_at')
        batch_op.drop_index('ix_phone_codes_phone')

    op.drop_table('phone_codes')  # SMS codes are short-lived; nothing worth migrating

    # Emails become unique (login / password reset by email). Normalise existing ones and keep
    # a duplicate address only on the oldest account, so the unique index can be created.
    bind = op.get_bind()
    users = sa.table("users", sa.column("id", sa.Integer), sa.column("email", sa.String))
    seen = set()
    for user_id, email in bind.execute(sa.select(users.c.id, users.c.email).order_by(users.c.id)).all():
        if email is None:
            continue
        clean = email.strip().lower() or None
        if clean in seen:
            clean = None
        if clean:
            seen.add(clean)
        if clean != email:
            bind.execute(users.update().where(users.c.id == user_id).values(email=clean))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.create_table('phone_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=16), nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_codes', schema=None) as batch_op:
        batch_op.create_index('ix_phone_codes_phone', ['phone'], unique=False)
        batch_op.create_index('ix_phone_codes_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_target'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_created_at'))

    op.drop_table('verification_codes')
    # ### end Alembic commands ###
