"""anonymous requests, agreement, response tracking

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 12:29:14.762159

"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fine', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_deliveries_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_deliveries_master_id'), ['master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_deliveries_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_deliveries_status'), ['status'], unique=False)

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missed_requests', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rating_penalty', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('client_token_hash', sa.String(length=64), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_orders_client_token_hash'), ['client_token_hash'], unique=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreement_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('agreement_version', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('agreement_version')
        batch_op.drop_column('agreement_accepted_at')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_client_token_hash'))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('client_token_hash')
        batch_op.drop_column('client_phone')
        batch_op.drop_column('client_name')

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_column('rating_penalty')
        batch_op.drop_column('missed_requests')

    with op.batch_alter_table('request_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_request_deliveries_order_id'))
        batch_op.drop_index(batch_op.f('ix_request_deliveries_master_id'))
        batch_op.drop_index(batch_op.f('ix_request_deliveries_deadline_at'))

    op.drop_table('request_deliveries')
    # ### end Alembic commands ###
